spring:
  application:
    name: "word-search-node"
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: true
server:
  display-name: "word-search-node"
  port: 8081

logging:
  level:
    org:
      springframework: ERROR