spring:
  application:
    name: "Word indexer GW"
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

logging:
  level:
    org:
      springframework: ERROR
    me:
      interair:
        wi:
          config: DEBUG